In [30]:
import numpy as np
import math

In [31]:
def FK(js):
    Ts = []

    c1 = math.cos(js[0])
    s1 = math.sin(js[0])
    c2 = math.cos(js[1])
    s2 = math.sin(js[1])
    c3 = math.cos(js[2])
    s3 = math.sin(js[2])
    c4 = math.cos(js[3])
    s4 = math.sin(js[3])
    c5 = math.cos(js[4])
    s5 = math.sin(js[4])

    a2 = 0.155
    a3 = 0.135
    d1 = 0.147
    d5 = 0.218

    Ts.append(np.matrix([[c1, 0, s1, 0], [s1, 0, -c1, 0], [0, 1, 0, d1], [0, 0, 0, 1]]))
    Ts.append(np.matrix([[c2, -s2, 0, a2*c2], [s2, c2, 0, a2*s2], [0, 0, 1,0], [0, 0, 0, 1]]))
    Ts.append(np.matrix([[c3, -s3, 0, a3*c3], [s3, c3, 0, a3*s3], [0, 0, 1, 0], [0, 0, 0, 1]]))
    Ts.append(np.matrix([[c4, 0, s4, 0], [s4, 0, -c4, 0], [0, 1, 0, 0], [0, 0, 0, 1]]))
    Ts.append(np.matrix([[c5, -s5, 0, 0], [s5, c5, 0, 0], [0, 0, 1, d5], [0, 0, 0, 1]]))

    return [Ts[0], Ts[0]*Ts[1], Ts[0]*Ts[1]*Ts[2], Ts[0]*Ts[1]*Ts[2]*Ts[3], Ts[0]*Ts[1]*Ts[2]*Ts[3]*Ts[4]]


def make_q(e, theta):
    return [e[0]*math.sin(theta/2), e[1]*math.sin(theta/2), e[2]*math.sin(theta/2), math.cos(theta/2)]


def my_cross(q, p):
    return [q[3]*p[0] - q[2]*p[1] + q[1]*p[2] + q[0]*p[3],
            q[2]*p[0] + q[3]*p[1] - q[0]*p[2] + q[1]*p[3],
            -q[1]*p[0] + q[0]*p[1] + q[3]*p[2] + q[2]*p[3],
            -q[0]*p[0] - q[1]*p[1] - q[2]*p[2] + q[3]*p[3]]

def fixPi(Js):
    js = Js
    for j in range(len(Js)):
      if js[j] > math.pi:
        js[j] = js[j] - int((js[j] + math.pi)/(2*math.pi))*2*math.pi
      elif js[j] < -math.pi:
        js[j] = js[j] - int((js[j]-math.pi)/(2*math.pi))*2*math.pi
    return js

In [32]:
theta = []
theta.append(0)
theta.append(np.pi/2)
theta.append(0)
theta.append(np.pi/2)
theta.append(0)
fk = FK(theta)
print(fk[0])
print(fk[1])
print(fk[2])
print(fk[3])
print(fk[4])

[[ 1.     0.     0.     0.   ]
 [ 0.     0.    -1.     0.   ]
 [ 0.     1.     0.     0.147]
 [ 0.     0.     0.     1.   ]]
[[ 6.12323400e-17 -1.00000000e+00  0.00000000e+00  9.49101269e-18]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17  0.00000000e+00  3.02000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 6.12323400e-17 -1.00000000e+00  0.00000000e+00  1.77573786e-17]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17  0.00000000e+00  4.37000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-1.00000000e+00  0.00000000e+00  1.22464680e-16  1.77573786e-17]
 [ 0.00000000e+00 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.22464680e-16  0.00000000e+00  1.00000000e+00  4.37000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-1.00000000e+00  0.00000000e+00  1.22464680e-16  4.44546788e-17]
 

In [5]:
x1 = 0
y1 = 0
z1 = 0.147

L = [0.147,0.155,0.135,0.218]

def theta0(p):

    if p[0]== 0 and p[1] == 0:
        theta = 0
    else:
        theta = math.atan2(p[0]),p[1]
    return theta

def theta2(p):
    L14 = math.sqrt(())


In [6]:
def AnalyticSolution(x,y,z,quaternion):
    L = [0.147,0.155,0.135,0.218]
    q = quaternion
    vx = 2*(q[0]*q[2] + q[3]*q[1])
    vy = 2*(q[1]*q[2] - q[3]*q[0])
    vz = q[3]**2 - q[0]**2 - q[1]**2 + q[2]**2

    x3 = x - L[3]*vx
    y3 = y - L[3]*vy
    z3 = z - L[3]*vz

    Theta0 = theta0([x,y,z])

    x1 = 0
    y1 = 0
    z1 = 0.147

    L13 = math.sqrt((x3 - x1)**2 + (y3 - y1)**2 + (z3 - L[0])**2)
    Theta2 = math.acos(-(L[1]**2 + L[2]**2 - L13**2)/(2*L[1]*L[2]))
    L03 = math.sqrt((x3 - x1)**2 + (y3 - y1)**2 + (z3)**2)
    Theta1_1 = math.acos((L[1]**2 + L13**2 - L[2]**2)/(2*L[1]*L13))
    Theta1_2 = math.acos((L[0]**2 + L13**2 - L03**2)/2*L[0]*L13)
    Theta1 = math.pi - (Theta1_1 + Theta1_2)

    xyz2 = FK(L, [Theta0, Theta1, 0, 0, 0, 0])
    x2 = xyz2[2][0, 3]
    y2 = xyz2[2][1, 3]
    z2 = xyz2[2][2, 3]

    L26_2 = (x - x2)**2 + (y - y2)**2 + (z - z2)**2
    Theta3 = math.acos(-((L[3] + L[4])**2 + (L[5] + L[6])**2 - L26_2)/(2*(L[3] + L[4])*(L[5] + L[6])))

    my_q = []
    my_q.append(make_q([0,0,1],Theta0))
    my_q.append(make_q([1,0,0],Theta1))
    my_q.append(make_q([1,0,0],Theta2))
    my_q.append(make_q([1,0,0],Theta3))

    my_Q = []
    my_Q.append(my_cross(my_q[0],my_q[1]))
    my_Q.append(my_cross(my_Q[0],my_q[2]))
    my_Q.append(my_cross(my_Q[1],my_q[3]))

    qx03 = my_Q[2][0]
    qy03 = my_Q[2][1]
    qz03 = my_Q[2][2]
    qw03 = my_Q[3][3]

    qx04 = q[0]
    qy04 = q[1]
    qz04 = q[2]
    qw04 = q[3]

    C5 = (qx03*qx04 + qy03*qy04)/(qx03**2 + qy03**2)
    S5 = (qx04*qx03 - qy04*qy03)/(qx03**2 + qy03**2)

    Theta4 = 2*math.atan2(S5,C5)

    js = fixPi([Theta0, Theta1, Theta2, Theta3, Theta4])

    return js

In [29]:
import random
js = [0,0,0,0,0]
random_js = []
random_js.append(random.uniform(-math.pi*17/18, math.pi*17/18))
random_js.append(random.uniform(-math.pi*100/180, math.pi*135/180))
random_js.append(random.uniform(-math.pi*12/18, math.pi*153/180))
random_js.append(random.uniform(-math.pi*27/18, math.pi*27/18))
random_js.append(random.uniform(-math.pi*12/18, math.pi*12/18))

print(random_js)

#random_jsから、手先座標[x, y, z], 姿勢qtnを導出
L = [0.1975, 0.1975, 0.340, 0.197, 0.143, 0.070, 0.035]
TTs = FK(random_js)

x = TTs[4][0, 3]
y = TTs[4][1, 3]
z = TTs[4][2, 3]
print(x,y,z)

[0.16091939824949408, 1.9455950207006751, -0.23555315125841791, 1.8635521567058566, 1.3002478623401408]
-0.16460049195095056 -0.026718436343386703 0.6229056975160094


In [22]:
print(random.uniform(-math.pi*12/18, math.pi*12/18))

-1.9794862027258204
